### ISSUE TITLE
NATSNoRespondersException in Producer

### ISSUE THREAD

**Issue by JaronrH** [memphisdev/memphis.net#15]
I'm trying to create my first producer against a local Docker instance for Memphis.  While I can get my producer to show up in the GUI, I am so far unable to produce any messages.  I don't have any experience with JetStream so not sure how proceed!  

Exception:
      NATS.Client.NATSNoRespondersException: No responders are available for the request.
         at NATS.Client.Connection.requestAsync(String subject, Byte[] headers, Byte[] data, Int32 offset, Int32 count, Int32 timeout, CancellationToken token)
         at NATS.Client.JetStream.JetStream.PublishAsyncInternal(String subject, Byte[] data, MsgHeader hdr, PublishOptions options)
         at Memphis.Client.Producer.MemphisProducer.ProduceAsync(Byte[] message, NameValueCollection headers, Int32 ackWaitSec, String messageId) in C:\****\Memphis.Client\Producer\MemphisProducer.cs:line 69

JetSteam Object in Debug:         
![image](https://user-images.githubusercontent.com/16034713/214163052-26b9d838-ea5f-4167-8944-45d44c2b5fce.png)

GUI showing Producer connected and active:
![image](https://user-images.githubusercontent.com/16034713/214163246-28708755-1314-4bb3-8e3a-a5d1d51eed7e.png)

**Comment by JaronrH** [comment]
Closing Issue -- Problem was in the Station Name.  I created a station named "SensorData" but that was changed to all lower-case by Memphis but not normalized to lowercase in the .NET SDK!  As soon as I changed the Station Name to "sensordata", everything worked.
