### ISSUE TITLE
Authorization Violation when creating a client.

### ISSUE THREAD

**Issue by godszerg86** [memphisdev/memphis.net#35]
```
AsyncErrorEvent, Connection: 352, Error: 'Authorization Violation'
AsyncErrorEvent, Connection: 352, Error: 'Authorization Violation'
ClosedEvent, Connection: 352
Exception: error occured, when connecting memphis
Memphis.Client.Exception.MemphisConnectionException: error occured, when connecting memphis
 ---> NATS.Client.NATSConnectionException: 'Authorization Violation'
   at NATS.Client.Connection.connect()
   at NATS.Client.ConnectionFactory.CreateConnection(Options opts)
   at Memphis.Client.MemphisClientFactory.CreateClient(ClientOptions opts) in D:\ChatGPT_projects\Mempis_test\memphis.net\src\Memphis.Client\MemphisClientFactory.cs:line 70
   --- End of inner exception stack trace ---
   at Memphis.Client.MemphisClientFactory.CreateClient(ClientOptions opts) in D:\ChatGPT_projects\Mempis_test\memphis.net\src\Memphis.Client\MemphisClientFactory.cs:line 80
   at Producer.ProducerApp.Main(String[] args) in D:\ChatGPT_projects\Mempis_test\Mempis_test\Program.cs:line 17
```

The application type token and user name created in the dashboard are correct. 
Steps to reproduce:

Run code snippet from:
examples/Producer/Program.cs

Memphis instance is running locally from docker-compose file.

This is what container logs:
```
memphis-memphis-cluster-1       | [1] 2023/04/01 00:01:13.333282 [ERR] 172.18.0.1:49530 - cid:232 - "v1.0.2.0:.NET:d0e60e3d-ca85-48d4-887a-5cf7665b1b21::REDUCTED" - handleConnectMessage: User REDUCTED: the provided hex string is not a valid ObjectID
```

**Comment by godszerg86** [comment]
Might be an issue with mongo db driver...
